### ISSUE TITLE
[Bug]: Merging objects might not work in many cases

### ISSUE THREAD

**Issue by fashxp** [pimcore/object-merger#24]
### Expected behavior

merging objects works without error

### Actual behavior

depending on data type it cannot work due to 

https://github.com/pimcore/object-merger/blob/4.x/src/Controller/AdminController.php#L289-L290

return type of `getDiffDataFromEditmode` might be different to expected value of `setValue` ... 

### Steps to reproduce

compare and try to merge `event` objects of demo application (e.g. `tags` field)

**Comment by mattamon** [comment]
@fashxp as mentioned in the other issue #21 this is not a problem with the object merger per se. 
We can always change the merger to check if the types match up, or we change the https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/ClassDefinition/Data/Multiselect.php#L275 this line to return an array instead of a string. 

I am not sure though where this would cause issues. 

Wdyt?

**Comment by mattamon** [comment]
partly resolved by https://github.com/pimcore/pimcore/pull/13965

**Comment by fashxp** [comment]
TODO: check, if there are other datatypes having the same problem and eventually find another solution for that...

**Comment by dvesh3** [comment]
Works for all other datatypes.
